const avatarUrlLookup = {
    a: "http://cdn.jsdelivr.net/gh/schmittyannic/images/eldenplanner/letters/letter-a.svg",
    b: "http://cdn.jsdelivr.net/gh/schmittyannic/images/eldenplanner/letters/letter-b.svg",
    c: "http://cdn.jsdelivr.net/gh/schmittyannic/images/eldenplanner/letters/letter-c.svg",
    d: "http://cdn.jsdelivr.net/gh/schmittyannic/images/eldenplanner/letters/letter-d.svg",
    e: "http://cdn.jsdelivr.net/gh/schmittyannic/images/eldenplanner/letters/letter-e.svg",
    f: "http://cdn.jsdelivr.net/gh/schmittyannic/images/eldenplanner/letters/letter-f.svg",
    g: "http://cdn.jsdelivr.net/gh/schmittyannic/images/eldenplanner/letters/letter-g.svg",
    h: "http://cdn.jsdelivr.net/gh/schmittyannic/images/eldenplanner/letters/letter-h.svg",
    i: "http://cdn.jsdelivr.net/gh/schmittyannic/images/eldenplanner/letters/letter-i.svg",
    j: "http://cdn.jsdelivr.net/gh/schmittyannic/images/eldenplanner/letters/letter-j.svg",
    k: "http://cdn.jsdelivr.net/gh/schmittyannic/images/eldenplanner/letters/letter-k.svg",
    l: "http://cdn.jsdelivr.net/gh/schmittyannic/images/eldenplanner/letters/letter-l.svg",
    m: "http://cdn.jsdelivr.net/gh/schmittyannic/images/eldenplanner/letters/letter-m.svg",
    n: "http://cdn.jsdelivr.net/gh/schmittyannic/images/eldenplanner/letters/letter-n.svg",
    o: "http://cdn.jsdelivr.net/gh/schmittyannic/images/eldenplanner/letters/letter-o.svg",
    p: "http://cdn.jsdelivr.net/gh/schmittyannic/images/eldenplanner/letters/letter-p.svg",
    q: "http://cdn.jsdelivr.net/gh/schmittyannic/images/eldenplanner/letters/letter-q.svg",
    r: "http://cdn.jsdelivr.net/gh/schmittyannic/images/eldenplanner/letters/letter-r.svg",
    s: "http://cdn.jsdelivr.net/gh/schmittyannic/images/eldenplanner/letters/letter-s.svg",
    t: "http://cdn.jsdelivr.net/gh/schmittyannic/images/eldenplanner/letters/letter-t.svg",
    u: "http://cdn.jsdelivr.net/gh/schmittyannic/images/eldenplanner/letters/letter-u.svg",
    v: "http://cdn.jsdelivr.net/gh/schmittyannic/images/eldenplanner/letters/letter-v.svg",
    w: "http://cdn.jsdelivr.net/gh/schmittyannic/images/eldenplanner/letters/letter-w.svg",
    x: "http://cdn.jsdelivr.net/gh/schmittyannic/images/eldenplanner/letters/letter-x.svg",
    y: "http://cdn.jsdelivr.net/gh/schmittyannic/images/eldenplanner/letters/letter-y.svg",
    z: "http://cdn.jsdelivr.net/gh/schmittyannic/images/eldenplanner/letters/letter-z.svg",
};

export default avatarUrlLookup